apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mvaj11zz4-nodejs 
  janus-idp.io/tekton: mvaj11zz4-nodejs
  backstage.io/kubernetes-id: mvaj11zz4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mvaj11zz4-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  